# Generated by Django 5.1.2 on 2024-10-31 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_tourregistration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tourregistration',
            old_name='staff_member',
            new_name='customer',
        ),
        migrations.RemoveField(
            model_name='tourregistration',
            name='customer_name',
        ),
    ]
